spring:
  application:
    name: gestao-entidades-api

  datasource:
    url: jdbc:postgresql://localhost:5432/gestao_entidades_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

gemini:
  api:
    key: "FUTURA_CHAVE"